### ISSUE TITLE
Investigate renaming course to 'teamwork'-course

### ISSUE THREAD

**Issue by svenvanderburg** [escience-academy/lesson-agile-escience#16]
Investigate whether the scope of the course should be a bit broader, i.e. include also other insights into teamwork and reflect the Teamwork SIG scope.

**Comment by svenvanderburg** [comment]
I vote for 'Teamwork for scientists'. Other ideas:
* Teamwork for eScientists
* Team science
* Teamwork for research software

'Teamwork for research software' it is!

**Comment by raar1** [comment]
What needs to be reviewed here exactly?
