### ISSUE TITLE
Episode 2: What is Agile and why

### ISSUE THREAD

**Issue by bpmweel** [escience-academy/lesson-agile-escience#2]
#### Learning Objectives
- List benefits of Agile mindset (2)
- Explain difference with Waterfall method (29)
- Describe Agile mindset (27)

Proposal for how to teach above objectives:
  - Introduce waterfall
  - introduction to agile from resource #2
  - Exercise on 12 principles from resource #2
  - Mention benefits of agile.

**Comment by svenvanderburg** [comment]
Fixed with #12
